version: '3.8'

services:
  library-app:
    container_name: library-app
    build:
      context: .
      dockerfile: Dockerfile
    image: library-app:latest
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - USER_PGSQL=${USER_PGSQL}
      - PASS_PGSQL=${PASS_PGSQL}
    volumes:
      - library-app:/app

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '12345678!'
      POSTGRES_DB: 'schwarz_db'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  library-app: